### ISSUE TITLE
all_face_masks and all_transformations files

### ISSUE THREAD

**Issue by fernandorovai** [marcoamonteiro/lip2lip_demo#1]
Hello, thanks for this nice repo.
I am trying to generate the video and I cannot find the files all_transformations.npy and all_face_masks.npy. Can you please guide me on how to get these compiled files?

Thanks

**Comment by fernandorovai** [comment]
Actually I figured it out. It belongs to the test feature extractor module. Thanks

**Comment by marcoamonteiro** [comment]
Sounds good.  Let me know if you run into any other issues
